FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ENV ASPNETCORE_URLS=http://+:80
WORKDIR /app

# Copy Web project folder
COPY ./ ./

# Publish our Web to a new folder
RUN dotnet publish ./SpaceparkWebApp.csproj -o ./publish

# Run published Web
ENTRYPOINT ["dotnet", "./publish/SpaceparkWebApp.dll"]